### PR TITLE
Add UNMS_NETFLOW_PORT

### PR DESCRIPTION
**Pull request by oliviermichaelis**
Adding an environment variable in order to set the netflow port to `2055` so that it's not read incorrectly from the environment. In my case it was somehow populated as `udp://10.43.78.183:2055`.

This fixes the issue mentioned in #29

### CODE REVIEW

**Comment by Nico640** [comment]
That's weird, UNMS_NETFLOW_PORT is already set by the Dockerfile. Also, I couldn't find a script in UNMS or netflow that would actually set that environment variable. Does the environment variable change back to `udp://10.43.78.183:2055` if you remove your fix?

**Comment by oliviermichaelis** [comment]
I redeployed the container and that's the output:
```
root@unms-0:/home/app/unms# echo $UNMS_NETFLOW_PORT
udp://10.43.78.183:2055
```
I really don't have any idea how and what is overwriting `UNMS_NETFLOW_PORT`. Would it be a good idea to move the environment variable from the Dockerfile to `root/etc/services.d/netflow/run` in order to prevent anything overwriting the environment variable?

**Comment by Nico640** [comment]
Yeah, shouldn't be an issue.

**Comment by oliviermichaelis** [comment]
Thanks! :)

**Pull request merged**
